### ISSUE TITLE
Declarative mappings in `tables.py` do not match the tables in the PostgreSQL database

### ISSUE THREAD

**Issue by Ahsoka** [Conbonbot/RS-Club-Bot#8]
The declarative mappings in [`tables.py`] do not match the tables in PostgreSQL database.

None of the PostgreSQL tables in `conbonbot` database have any primary keys, despite the fact they are outline in [`tables.py`] file.  This is because when the tables were first being created, the following SQL commands do not include any primary keys.
https://github.com/Conbonbot/RS-Club-Bot/blob/729cd328195ac8dfee05a71811b3f8e4a0f62f87/bot.py#L46-L57

These lines of SQL are later executed by these lines:
https://github.com/Conbonbot/RS-Club-Bot/blob/729cd328195ac8dfee05a71811b3f8e4a0f62f87/bot.py#L77-L79

This is probably a major source of issues, however, more investigation will be needed to determine the veracity of this.

[`tables.py`]: https://github.com/Conbonbot/RS-Club-Bot/blob/master/routines/tables.py

**Comment by Ahsoka** [comment]
I would highly recommend using the SQLAlchemy's automated table creation instead of implementing it yourself.

This can be achieved like this:
```py
# Base is the declarative base you created with the declarative_base() function

async with engine.begin() as conn:
    await conn.run_sync(Base.metadata.create_all)
```

**Comment by connorharv** [comment]
Issue #8 closed with most recent push
